const JOGOS_MUNDIAL = [
  {"date": "Thu, Jun 11", "match": "🇲🇽 Mexico vs. South Africa 🇿🇦", "group": "Group A", "time": "20:00", "broadcaster": "TVI / Sport TV 5 / LiveMode TV (YouTube)"},
  {"date": "Fri, Jun 12", "match": "🇰🇷 South Korea vs. Czechia 🇨🇿", "group": "Group A", "time": "03:00", "broadcaster": "Sport TV 5"},
  {"date": "Fri, Jun 12", "match": "🇨🇦 Canada vs. Bosnia & Herzegovina 🇧🇦", "group": "Group B", "time": "20:00", "broadcaster": "SIC / Sport TV 5 / LiveMode TV (YouTube)"},
  {"date": "Sat, Jun 13", "match": "🇺🇸 USA vs. Paraguay 🇵🇾", "group": "Group D", "time": "02:00", "broadcaster": "Sport TV 5"},
  {"date": "Sat, Jun 13", "match": "🇶🇦 Qatar vs. Switzerland 🇨🇭", "group": "Group B", "time": "20:00", "broadcaster": "Sport TV 5"},
  {"date": "Sat, Jun 13", "match": "🇧🇷 Brazil vs. Morocco 🇲🇦", "group": "Group C", "time": "23:00", "broadcaster": "Sport TV 5 / LiveMode TV (YouTube)"},
  {"date": "Sun, Jun 14", "match": "🇭🇹 Haiti vs. Scotland 🏴󠁧󠁢󠁳󠁣󠁴󠁿", "group": "Group C", "time": "02:00", "broadcaster": "Sport TV 5"},
  {"date": "Sun, Jun 14", "match": "🇦🇺 Australia vs. Türkiye 🇹🇷", "group": "Group D", "time": "05:00", "broadcaster": "Sport TV 5"},
  {"date": "Sun, Jun 14", "match": "🇩🇪 Germany vs. Curaçao 🇨🇼", "group": "Group E", "time": "18:00", "broadcaster": "Sport TV 5 / LiveMode TV (YouTube)"},
  {"date": "Sun, Jun 14", "match": "🇳🇱 Netherlands vs. Japan 🇯🇵", "group": "Group F", "time": "21:00", "broadcaster": "Sport TV 5"},
  {"date": "Mon, Jun 15", "match": "🇨🇮 Côte d'Ivoire vs. Ecuador 🇪🇨", "group": "Group E", "time": "00:00", "broadcaster": "Sport TV 5"},
  {"date": "Mon, Jun 15", "match": "🇸🇪 Sweden vs. Tunisia 🇹🇳", "group": "Group F", "time": "03:00", "broadcaster": "Sport TV 5"},
  {"date": "Mon, Jun 15", "match": "🇪🇸 Spain vs. Cabo Verde 🇨🇻", "group": "Group H", "time": "17:00", "broadcaster": "Sport TV 5 / LiveMode TV (YouTube)"},
  {"date": "Mon, Jun 15", "match": "🇧🇪 Belgium vs. Egypt 🇪🇬", "group": "Group G", "time": "20:00", "broadcaster": "Sport TV 5"},
  {"date": "Mon, Jun 15", "match": "🇸🇦 Saudi Arabia vs. Uruguay 🇺🇾", "group": "Group H", "time": "23:00", "broadcaster": "Sport TV 5"},
  {"date": "Tue, Jun 16", "match": "🇮🇷 IR Iran vs. New Zealand 🇳🇿", "group": "Group G", "time": "02:00", "broadcaster": "Sport TV 5"},
  {"date": "Tue, Jun 16", "match": "🇫🇷 France vs. Senegal 🇸🇳", "group": "Group I", "time": "20:00", "broadcaster": "RTP / Sport TV 5 / LiveMode TV (YouTube)"},
  {"date": "Tue, Jun 16", "match": "🇮🇶 Iraq vs. Norway 🇳🇴", "group": "Group I", "time": "23:00", "broadcaster": "Sport TV 5"},
  {"date": "Wed, Jun 17", "match": "🇦🇷 Argentina vs. Algeria 🇩🇿", "group": "Group J", "time": "02:00", "broadcaster": "Sport TV 5"},
  {"date": "Wed, Jun 17", "match": "🇦🇺 Austria vs. Jordan 🇯🇴", "group": "Group J", "time": "05:00", "broadcaster": "Sport TV 5"},
  {"date": "Wed, Jun 17", "match": "🇵🇹 Portugal vs. Congo DR 🇨🇩", "group": "Group K", "time": "18:00", "broadcaster": "SIC / Sport TV 5 / LiveMode TV (YouTube)"},
  {"date": "Wed, Jun 17", "match": "🏴󠁧󠁢󠁥󠁮󠁧󠁿 England vs. Croatia 🇭🇷", "group": "Group L", "time": "21:00", "broadcaster": "Sport TV 5"},
  {"date": "Thu, Jun 18", "match": "🇬🇭 Ghana vs. Panama 🇵🇦", "group": "Group L", "time": "00:00", "broadcaster": "Sport TV 5"},
  {"date": "Thu, Jun 18", "match": "🇺🇿 Uzbekistan vs. Colombia 🇨🇴", "group": "Group K", "time": "03:00", "broadcaster": "Sport TV 5"},
  {"date": "Thu, Jun 18", "match": "🇨🇿 Czechia vs. South Africa 🇿🇦", "group": "Group A", "time": "17:00", "broadcaster": "Sport TV 5"},
  {"date": "Thu, Jun 18", "match": "🇨🇭 Switzerland vs. Bosnia & Herzegovina 🇧🇦", "group": "Group B", "time": "20:00", "broadcaster": "RTP / Sport TV 5 / LiveMode TV (YouTube)"},
  {"date": "Thu, Jun 18", "match": "🇨🇦 Canada vs. Qatar 🇶🇦", "group": "Group B", "time": "23:00", "broadcaster": "Sport TV 5"},
  {"date": "Fri, Jun 19", "match": "🇲🇽 Mexico vs. Korea Republic 🇰🇷", "group": "Group A", "time": "02:00", "broadcaster": "Sport TV 5"},
  {"date": "Fri, Jun 19", "match": "🇺🇸 USA vs. Australia 🇦🇺", "group": "Group D", "time": "20:00", "broadcaster": "Sport TV 5"},
  {"date": "Fri, Jun 19", "match": "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scotland vs. Morocco 🇲🇦", "group": "Group C", "time": "23:00", "broadcaster": "Sport TV 5"},
  {"date": "Sat, Jun 20", "match": "🇧🇷 Brazil vs. Haiti 🇭🇹", "group": "Group C", "time": "02:00", "broadcaster": "Sport TV 5 / LiveMode TV (YouTube)"},
  {"date": "Sat, Jun 20", "match": "🇹🇷 Türkiye vs. Paraguay 🇵🇾", "group": "Group D", "time": "05:00", "broadcaster": "Sport TV 5"},
  {"date": "Sat, Jun 20", "match": "🇳🇱 Netherlands vs. Sweden 🇸🇪", "group": "Group F", "time": "18:00", "broadcaster": "Sport TV 5"},
  {"date": "Sat, Jun 20", "match": "🇩🇪 Germany vs. Côte d'Ivoire 🇨🇮", "group": "Group E", "time": "21:00", "broadcaster": "TVI / Sport TV 5 / LiveMode TV (YouTube)"},
  {"date": "Sun, Jun 21", "match": "🇪🇨 Ecuador vs. Curaçao 🇨🇼", "group": "Group E", "time": "00:00", "broadcaster": "Sport TV 5"},
  {"date": "Sun, Jun 21", "match": "🇹🇳 Tunisia vs. Japan 🇯🇵", "group": "Group F", "time": "05:00", "broadcaster": "Sport TV 5"},
  {"date": "Sun, Jun 21", "match": "🇪🇸 Spain vs. Saudi Arabia 🇸🇦", "group": "Group H", "time": "17:00", "broadcaster": "Sport TV 5 / LiveMode TV (YouTube)"},
  {"date": "Sun, Jun 21", "match": "🇧🇪 Belgium vs. IR Iran 🇮🇷", "group": "Group G", "time": "20:00", "broadcaster": "Sport TV 5"},
  {"date": "Sun, Jun 21", "match": "🇺🇾 Uruguay vs. Cabo Verde 🇨🇻", "group": "Group H", "time": "23:00", "broadcaster": "Sport TV 5"},
  {"date": "Mon, Jun 22", "match": "🇳🇿 New Zealand vs. Egypt 🇪🇬", "group": "Group G", "time": "02:00", "broadcaster": "Sport TV 5"},
  {"date": "Mon, Jun 22", "match": "🇫🇷 France vs. Iraq 🇮🇶", "group": "Group I", "time": "20:00", "broadcaster": "Sport TV 5 / LiveMode TV (YouTube)"},
  {"date": "Mon, Jun 22", "match": "🇳🇴 Norway vs. Senegal 🇸🇳", "group": "Group I", "time": "23:00", "broadcaster": "Sport TV 5"},
  {"date": "Tue, Jun 23", "match": "🇦🇷 Argentina vs. Austria 🇦🇹", "group": "Group J", "time": "02:00", "broadcaster": "Sport TV 5"},
  {"date": "Tue, Jun 23", "match": "🇯🇴 Jordan vs. Algeria 🇩🇿", "group": "Group J", "time": "05:00", "broadcaster": "Sport TV 5"},
  {"date": "Tue, Jun 23", "match": "🇵🇹 Portugal vs. Uzbekistan 🇺🇿", "group": "Group K", "time": "18:00", "broadcaster": "TVI / Sport TV 5 / LiveMode TV (YouTube)"},
  {"date": "Tue, Jun 23", "match": "🏴󠁧󠁢󠁥󠁮󠁧󠁿 England vs. Ghana 🇬🇭", "group": "Group L", "time": "21:00", "broadcaster": "Sport TV 5"},
  {"date": "Wed, Jun 24", "match": "🇵🇦 Panama vs. Croatia 🇭🇷", "group": "Group L", "time": "00:00", "broadcaster": "Sport TV 5"},
  {"date": "Wed, Jun 24", "match": "🇨🇴 Colombia vs. Congo DR 🇨🇩", "group": "Group K", "time": "03:00", "broadcaster": "Sport TV 5"},
  {"date": "Wed, Jun 24", "match": "🇨🇿 Czechia vs. Mexico 🇲🇽", "group": "Group A", "time": "21:00", "broadcaster": "Sport TV 1"},
  {"date": "Wed, Jun 24", "match": "🇿🇦 South Africa vs. Korea Republic 🇰🇷", "group": "Group A", "time": "21:00", "broadcaster": "Sport TV 5"},
  {"date": "Thu, Jun 25", "match": "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scotland vs. Brazil 🇧🇷", "group": "Group C", "time": "00:00", "broadcaster": "Sport TV 5 / LiveMode TV (YouTube)"},
  {"date": "Thu, Jun 25", "match": "🇲🇦 Morocco vs. Haiti 🇭🇹", "group": "Group C", "time": "00:00", "broadcaster": "Sport TV 1"},
  {"date": "Thu, Jun 25", "match": "🇨🇭 Switzerland vs. Canada 🇨🇦", "group": "Group B", "time": "03:00", "broadcaster": "Sport TV 5"},
  {"date": "Thu, Jun 25", "match": "🇧🇦 Bosnia & Herzegovina vs. Qatar 🇶🇦", "group": "Group B", "time": "03:00", "broadcaster": "Sport TV 1"},
  {"date": "Thu, Jun 25", "match": "🇨🇼 Curaçao vs. Côte d'Ivoire 🇨🇮", "group": "Group E", "time": "20:00", "broadcaster": "Sport TV 1"},
  {"date": "Thu, Jun 25", "match": "🇪🇨 Ecuador vs. Germany 🇩🇪", "group": "Group E", "time": "20:00", "broadcaster": "SIC / Sport TV 5"},
  {"date": "Thu, Jun 25", "match": "🇯🇵 Japan vs. Sweden 🇸🇪", "group": "Group F", "time": "23:00", "broadcaster": "Sport TV 5"},
  {"date": "Thu, Jun 25", "match": "🇹🇳 Tunisia vs. Netherlands 🇳🇱", "group": "Group F", "time": "23:00", "broadcaster": "Sport TV 1"},
  {"date": "Fri, Jun 26", "match": "🇹🇷 Türkiye vs. USA 🇺🇸", "group": "Group D", "time": "02:00", "broadcaster": "Sport TV 5 / LiveMode TV (YouTube)"},
  {"date": "Fri, Jun 26", "match": "🇵🇾 Paraguay vs. Australia 🇦🇺", "group": "Group D", "time": "02:00", "broadcaster": "Sport TV 1"},
  {"date": "Fri, Jun 26", "match": "🇺🇾 Uruguay vs. Spain 🇪🇸", "group": "Group H", "time": "20:00", "broadcaster": "Sport TV 1"},
  {"date": "Fri, Jun 26", "match": "🇨🇻 Cabo Verde vs. Saudi Arabia 🇸🇦", "group": "Group H", "time": "20:00", "broadcaster": "Sport TV 5"},
  {"date": "Fri, Jun 26", "match": "🇳🇴 Norway vs. France 🇫🇷", "group": "Group I", "time": "23:00", "broadcaster": "TVI / Sport TV 5"},
  {"date": "Fri, Jun 26", "match": "🇸🇳 Senegal vs. Iraq 🇮🇶", "group": "Group I", "time": "23:00", "broadcaster": "Sport TV 1"},
  {"date": "Sat, Jun 27", "match": "🇪🇬 Egypt vs. IR Iran 🇮🇷", "group": "Group G", "time": "02:00", "broadcaster": "Sport TV 5"},
  {"date": "Sat, Jun 27", "match": "🇳🇿 New Zealand vs. Belgium 🇧🇪", "group": "Group G", "time": "02:00", "broadcaster": "Sport TV 1"},
  {"date": "Sat, Jun 27", "match": "🇩🇿 Algeria vs. Austria 🇦🇹", "group": "Group J", "time": "20:00", "broadcaster": "Sport TV 5"},
  {"date": "Sat, Jun 27", "match": "🇯🇴 Jordan vs. Argentina 🇦🇷", "group": "Group J", "time": "20:00", "broadcaster": "Sport TV 1"},
  {"date": "Sat, Jun 27", "match": "🇵🇦 Panama vs. England 🏴󠁧󠁢󠁥󠁮󠁧󠁿", "group": "Group L", "time": "23:00", "broadcaster": "Sport TV 5"},
  {"date": "Sat, Jun 27", "match": "🇭🇷 Croatia vs. Ghana 🇬🇭", "group": "Group L", "time": "23:00", "broadcaster": "Sport TV 1"},
  {"date": "Sun, Jun 28", "match": "🇨🇴 Colombia vs. Portugal 🇵🇹", "group": "Group K", "time": "00:30", "broadcaster": "RTP / Sport TV 5 / LiveMode TV (YouTube)"},
  {"date": "Sun, Jun 28", "match": "🇨🇩 Congo DR vs. Uzbekistan 🇺🇿", "group": "Group K", "time": "00:30", "broadcaster": "Sport TV 1"}
];
