// Base de dados fixa dos 72 jogos da Fase de Grupos
const JOGOS_MUNDIAL = [
  { date: "Thu, Jun 11", match: "🇲🇽 Mexico vs. South Africa 🇿🇦", group: "Group A", time: "20:00", broadcaster: "TVI / Sport TV 5 / CazéTV" },
  { date: "Fri, Jun 12", match: "🇰🇷 South Korea vs. Czechia 🇨🇿", group: "Group A", time: "03:00", broadcaster: "Sport TV 5" },
  { date: "Fri, Jun 12", match: "🇨🇦 Canada vs. Bosnia & Herzegovina 🇧🇦", group: "Group B", time: "20:00", broadcaster: "SIC / Sport TV 5 / CazéTV" },
  { date: "Sat, Jun 13", match: "🇺🇸 USA vs. Paraguay 🇵🇾", group: "Group D", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Sat, Jun 13", match: "🇶🇦 Qatar vs. Switzerland 🇨🇭", group: "Group B", time: "20:00", broadcaster: "Sport TV 5" },
  { date: "Sun, Jun 14", match: "🇩🇿 Algeria vs. Poland 🇵🇱", group: "Group D", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Sun, Jun 14", match: "🇺🇾 Uruguay vs. Jamaica 🇯🇲", group: "Group C", time: "20:00", broadcaster: "SIC / Sport TV 5 / CazéTV" },
  { date: "Mon, Jun 15", match: "🇨🇴 Colombia vs. Oman 🇴🇲", group: "Group E", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Mon, Jun 15", match: "🇯🇵 Japan vs. Nigeria 🇳🇬", group: "Group C", time: "18:00", broadcaster: "RTP 1 / Sport TV 5" },
  { date: "Mon, Jun 15", match: "🇩🇰 Denmark vs. Venezuela 🇻🇪", group: "Group E", time: "21:00", broadcaster: "Sport TV 5" },
  { date: "Tue, Jun 16", match: "🇦🇷 Argentina vs. Australia 🇦🇺", group: "Group F", time: "02:00", broadcaster: "Sport TV 5 / CazéTV" },
  { date: "Tue, Jun 16", match: "🇸🇪 Sweden vs. Saudi Arabia 🇸🇦", group: "Group F", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Tue, Jun 16", match: "🇮🇷 Iran vs. Chile 🇨🇱", group: "Group H", time: "21:00", broadcaster: "Sport TV 5" },
  { date: "Wed, Jun 17", match: "🇪🇸 Spain vs. Tunisia 🇹🇳", group: "Group G", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Wed, Jun 17", match: "🇩🇪 Germany vs. New Zealand 🇳🇿", group: "Group G", time: "15:00", broadcaster: "Sport TV 5" },
  { date: "Wed, Jun 17", match: "🇵🇹 Portugal vs. Congo DR 🇨🇩", group: "Group K", time: "18:00", broadcaster: "SIC / Sport TV 5 / CazéTV" },
  { date: "Wed, Jun 17", match: "🇫🇷 France vs. Panama 🇵🇦", group: "Group H", time: "21:00", broadcaster: "RTP 1 / Sport TV 5" },
  { date: "Thu, Jun 18", match: "🇮🇹 Italy vs. Cameroon 🇨🇲", group: "Group I", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Thu, Jun 18", match: "🇳🇱 Netherlands vs. Honduras 🇭🇳", group: "Group I", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Thu, Jun 18", match: "🇧🇷 Brazil vs. UAE 🇦🇪", group: "Group L", time: "21:00", broadcaster: "TVI / Sport TV 5 / CazéTV" },
  { date: "Fri, Jun 19", match: "🇧🇪 Belgium vs. Uzbekistan 🇺🇿", group: "Group J", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Fri, Jun 19", match: "🇪🇨 Ecuador vs. Ivory Coast 🇨🇮", group: "Group J", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Fri, Jun 19", match: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 England vs. Peru 🇵🇪", group: "Group L", time: "21:00", broadcaster: "Sport TV 5" },
  { date: "Sat, Jun 20", match: "🇲🇦 Morocco vs. Iraq 🇮🇶", group: "Group K", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Sat, Jun 20", match: "🇲🇽 Mexico vs. South Korea 🇰🇷", group: "Group A", time: "18:00", broadcaster: "TVI / Sport TV 5 / CazéTV" },
  { date: "Sat, Jun 20", match: "🇨🇦 Canada vs. Qatar 🇶🇦", group: "Group B", time: "21:00", broadcaster: "Sport TV 5" },
  { date: "Sun, Jun 21", match: "🇿🇦 South Africa vs. Czechia 🇨🇿", group: "Group A", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Sun, Jun 21", match: "🇧🇦 Bosnia & Herzegovina vs. Switzerland 🇨🇭", group: "Group B", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Sun, Jun 21", match: "🇺🇸 USA vs. Algeria 🇩🇿", group: "Group D", time: "21:00", broadcaster: "RTP 1 / Sport TV 5" },
  { date: "Mon, Jun 22", match: "🇵🇾 Paraguay vs. Poland 🇵🇱", group: "Group D", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Mon, Jun 22", match: "🇺🇾 Uruguay vs. Japan 🇯🇵", group: "Group C", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Mon, Jun 22", match: "🇯🇲 Jamaica vs. Nigeria 🇳🇬", group: "Group C", time: "21:00", broadcaster: "Sport TV 5" },
  { date: "Tue, Jun 23", match: "🇨🇴 Colombia vs. Denmark 🇩🇰", group: "Group E", time: "02:00", broadcaster: "Sport TV 5 / CazéTV" },
  { date: "Tue, Jun 23", match: "🇴🇲 Oman vs. Venezuela 🇻🇪", group: "Group E", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Tue, Jun 23", match: "🇦🇷 Argentina vs. Sweden 🇸🇪", group: "Group F", time: "21:00", broadcaster: "SIC / Sport TV 5 / CazéTV" },
  { date: "Wed, Jun 24", match: "🇦🇺 Australia vs. Saudi Arabia 🇸🇦", group: "Group F", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Wed, Jun 24", match: "🇪🇸 Spain vs. Germany 🇩🇪", group: "Group G", time: "18:00", broadcaster: "TVI / Sport TV 5 / CazéTV" },
  { date: "Wed, Jun 24", match: "🇹🇳 Tunisia vs. New Zealand 🇳🇿", group: "Group G", time: "21:00", broadcaster: "Sport TV 5" },
  { date: "Thu, Jun 25", match: "🇫🇷 France vs. Iran 🇮🇷", group: "Group H", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Thu, Jun 25", match: "🇵🇦 Panama vs. Chile 🇨🇱", group: "Group H", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Thu, Jun 25", match: "🇳🇱 Netherlands vs. Italy 🇮🇹", group: "Group I", time: "21:00", broadcaster: "RTP 1 / Sport TV 5" },
  { date: "Fri, Jun 26", match: "🇭🇳 Honduras vs. Cameroon 🇨🇲", group: "Group I", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Fri, Jun 26", match: "🇪🇨 Ecuador vs. Belgium 🇧🇪", group: "Group J", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Fri, Jun 26", match: "🇨🇮 Ivory Coast vs. Uzbekistan 🇺🇿", group: "Group J", time: "21:00", broadcaster: "Sport TV 5" },
  { date: "Sat, Jun 27", match: "🇧🇷 Brazil vs. England 🏴󠁧󠁢󠁥󠁮󠁧󠁿", group: "Group L", time: "02:00", broadcaster: "SIC / Sport TV 5 / CazéTV" },
  { date: "Sat, Jun 27", match: "🇦🇪 UAE vs. Peru 🇵🇪", group: "Group L", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Sat, Jun 27", match: "🇵🇹 Portugal vs. Morocco 🇲🇦", group: "Group K", time: "21:00", broadcaster: "RTP 1 / Sport TV 5 / CazéTV" },
  { date: "Sun, Jun 28", match: "🇨🇩 Congo DR vs. Iraq 🇮🇶", group: "Group K", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Sun, Jun 28", match: "🇨🇿 Czechia vs. Mexico 🇲🇽", group: "Group A", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Sun, Jun 28", match: "🇿🇦 South Africa vs. South Korea 🇰🇷", group: "Group A", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Mon, Jun 29", match: "🇨🇭 Switzerland vs. Canada 🇨🇦", group: "Group B", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Mon, Jun 29", match: "🇧🇦 Bosnia & Herzegovina vs. Qatar 🇶🇦", group: "Group B", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Mon, Jun 29", match: "🇵🇱 Poland vs. USA 🇺🇸", group: "Group D", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Mon, Jun 29", match: "🇵🇾 Paraguay vs. Algeria 🇩🇿", group: "Group D", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Tue, Jun 30", match: "🇳🇬 Nigeria vs. Uruguay 🇺🇾", group: "Group C", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Tue, Jun 30", match: "🇯🇲 Jamaica vs. Japan 🇯🇵", group: "Group C", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Tue, Jun 30", match: "🇻🇪 Venezuela vs. Colombia 🇨🇴", group: "Group E", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Tue, Jun 30", match: "🇴🇲 Oman vs. Denmark 🇩🇰", group: "Group E", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Wed, Jul 01", match: "🇸🇦 Saudi Arabia vs. Argentina 🇦🇷", group: "Group F", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Wed, Jul 01", match: "🇦🇺 Australia vs. Sweden 🇸🇪", group: "Group F", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Wed, Jul 01", match: "🇳🇿 New Zealand vs. Spain 🇪🇸", group: "Group G", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Wed, Jul 01", match: "🇹🇳 Tunisia vs. Germany 🇩🇪", group: "Group G", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Thu, Jul 02", match: "🇨🇱 Chile vs. France 🇫🇷", group: "Group H", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Thu, Jul 02", match: "🇵🇦 Panama vs. Iran 🇮🇷", group: "Group H", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Thu, Jul 02", match: "🇨🇲 Cameroon vs. Netherlands 🇳🇱", group: "Group I", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Thu, Jul 02", match: "🇭🇳 Honduras vs. Italy 🇮🇹", group: "Group I", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Fri, Jul 03", match: "🇺🇿 Uzbekistan vs. Ecuador 🇪🇨", group: "Group J", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Fri, Jul 03", match: "🇨🇮 Ivory Coast vs. Belgium 🇧🇪", group: "Group J", time: "02:00", broadcaster: "Sport TV 5" },
  { date: "Fri, Jul 03", match: "🇵🇪 Peru vs. Brazil 🇧🇷", group: "Group L", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Fri, Jul 03", match: "🇦🇪 UAE vs. England 🏴󠁧󠁢󠁥󠁮󠁧󠁿", group: "Group L", time: "18:00", broadcaster: "Sport TV 5" },
  { date: "Sat, Jul 04", match: "🇮🇶 Iraq vs. Portugal 🇵🇹", group: "Group K", time: "02:00", broadcaster: "TVI / Sport TV 5 / CazéTV" },
  { date: "Sat, Jul 04", match: "🇲🇦 Morocco vs. Congo DR 🇨🇩", group: "Group K", time: "02:00", broadcaster: "Sport TV 5" }
];
